// Dữ liệu danh sách trường đại học và ngành đào tạo
const universitiesData = [
  {
    id: 1,
    schoolCode: "BKA",
    schoolName: "Đại học Bách Khoa Hà Nội",
    majorName: "Khoa học Máy tính (IT1)",
    majorCode: "7480101",
    category: "Công nghệ thông tin",
    subjectGroups: ["A00", "A01"],
    benchmarkScore: 28.53,
    tuitionFee: "30 - 45 triệu/năm",
    location: "Hà Nội",
    quota: 300,
    website: "https://hust.edu.vn"
  },
  {
    id: 2,
    schoolCode: "BKA",
    schoolName: "Đại học Bách Khoa Hà Nội",
    majorName: "Kỹ thuật Điều khiển & Tự động hóa",
    majorCode: "7520216",
    category: "Kỹ thuật - Công nghệ",
    subjectGroups: ["A00", "A01"],
    benchmarkScore: 26.85,
    tuitionFee: "28 - 35 triệu/năm",
    location: "Hà Nội",
    quota: 250,
    website: "https://hust.edu.vn"
  },
  {
    id: 3,
    schoolCode: "NEU",
    schoolName: "Đại học Kinh tế Quốc dân",
    majorName: "Quản trị Kinh doanh",
    majorCode: "7340101",
    category: "Kinh tế - Quản lý",
    subjectGroups: ["A00", "A01", "D01", "D07"],
    benchmarkScore: 27.20,
    tuitionFee: "22 - 32 triệu/năm",
    location: "Hà Nội",
    quota: 350,
    website: "https://neu.edu.vn"
  },
  {
    id: 4,
    schoolCode: "NEU",
    schoolName: "Đại học Kinh tế Quốc dân",
    majorName: "Tài chính - Ngân hàng",
    majorCode: "7340201",
    category: "Kinh tế - Quản lý",
    subjectGroups: ["A00", "A01", "D01", "D07"],
    benchmarkScore: 26.90,
    tuitionFee: "22 - 32 triệu/năm",
    location: "Hà Nội",
    quota: 280,
    website: "https://neu.edu.vn"
  },
  {
    id: 5,
    schoolCode: "FTU",
    schoolName: "Đại học Ngoại Thương",
    majorName: "Kinh tế Quốc tế",
    majorCode: "7310106",
    category: "Kinh tế - Quản lý",
    subjectGroups: ["A00", "A01", "D01", "D07"],
    benchmarkScore: 28.15,
    tuitionFee: "25 - 40 triệu/năm",
    location: "Hà Nội",
    quota: 200,
    website: "https://ftu.edu.vn"
  },
  {
    id: 6,
    schoolCode: "FTU",
    schoolName: "Đại học Ngoại Thương",
    majorName: "Marketing số (Digital Marketing)",
    majorCode: "7340115",
    category: "Kinh tế - Quản lý",
    subjectGroups: ["A00", "A01", "D01"],
    benchmarkScore: 27.80,
    tuitionFee: "28 - 45 triệu/năm",
    location: "Hà Nội",
    quota: 150,
    website: "https://ftu.edu.vn"
  },
  {
    id: 7,
    schoolCode: "QHI",
    schoolName: "Trường Đại học Công nghệ - ĐHQGHN",
    majorName: "Công nghệ Thông tin",
    majorCode: "7480201",
    category: "Công nghệ thông tin",
    subjectGroups: ["A00", "A01"],
    benchmarkScore: 27.95,
    tuitionFee: "35 - 40 triệu/năm",
    location: "Hà Nội",
    quota: 220,
    website: "https://uet.vnu.edu.vn"
  },
  {
    id: 8,
    schoolCode: "QHI",
    schoolName: "Trường Đại học Công nghệ - ĐHQGHN",
    majorName: "Trí tuệ Nhân tạo & Robot",
    majorCode: "7480107",
    category: "Công nghệ thông tin",
    subjectGroups: ["A00", "A01"],
    benchmarkScore: 27.60,
    tuitionFee: "38 - 42 triệu/năm",
    location: "Hà Nội",
    quota: 120,
    website: "https://uet.vnu.edu.vn"
  },
  {
    id: 9,
    schoolCode: "YHN",
    schoolName: "Đại học Y Hà Nội",
    majorName: "Y khoa (Bác sĩ Đa khoa)",
    majorCode: "7720101",
    category: "Y - Dược",
    subjectGroups: ["B00"],
    benchmarkScore: 28.25,
    tuitionFee: "55 - 60 triệu/năm",
    location: "Hà Nội",
    quota: 400,
    website: "https://hmu.edu.vn"
  },
  {
    id: 10,
    schoolCode: "YHN",
    schoolName: "Đại học Y Hà Nội",
    majorName: "Răng Hàm Mặt",
    majorCode: "7720501",
    category: "Y - Dược",
    subjectGroups: ["B00"],
    benchmarkScore: 27.85,
    tuitionFee: "55 - 60 triệu/năm",
    location: "Hà Nội",
    quota: 100,
    website: "https://hmu.edu.vn"
  },
  {
    id: 11,
    schoolCode: "QSB",
    schoolName: "Đại học Bách Khoa - ĐHQG TP.HCM",
    majorName: "Khoa học Máy tính",
    majorCode: "7480101",
    category: "Công nghệ thông tin",
    subjectGroups: ["A00", "A01"],
    benchmarkScore: 27.50,
    tuitionFee: "30 - 40 triệu/năm",
    location: "TP. Hồ Chí Minh",
    quota: 280,
    website: "https://hcmut.edu.vn"
  },
  {
    id: 12,
    schoolCode: "QSB",
    schoolName: "Đại học Bách Khoa - ĐHQG TP.HCM",
    majorName: "Kỹ thuật Hóa học",
    majorCode: "7520301",
    category: "Kỹ thuật - Công nghệ",
    subjectGroups: ["A00", "B00", "D07"],
    benchmarkScore: 24.20,
    tuitionFee: "28 - 32 triệu/năm",
    location: "TP. Hồ Chí Minh",
    quota: 200,
    website: "https://hcmut.edu.vn"
  },
  {
    id: 13,
    schoolCode: "UEH",
    schoolName: "Đại học Kinh tế TP.HCM (UEH)",
    majorName: "Logistics và Quản lý Chuỗi cung ứng",
    majorCode: "7510605",
    category: "Kinh tế - Quản lý",
    subjectGroups: ["A00", "A01", "D01", "D07"],
    benchmarkScore: 27.10,
    tuitionFee: "32 - 40 triệu/năm",
    location: "TP. Hồ Chí Minh",
    quota: 250,
    website: "https://ueh.edu.vn"
  },
  {
    id: 14,
    schoolCode: "UEH",
    schoolName: "Đại học Kinh tế TP.HCM (UEH)",
    majorName: "Thương mại Điện tử",
    majorCode: "7340122",
    category: "Kinh tế - Quản lý",
    subjectGroups: ["A00", "A01", "D01", "D07"],
    benchmarkScore: 26.75,
    tuitionFee: "30 - 38 triệu/năm",
    location: "TP. Hồ Chí Minh",
    quota: 180,
    website: "https://ueh.edu.vn"
  },
  {
    id: 15,
    schoolCode: "FPT",
    schoolName: "Đại học FPT",
    majorName: "Kỹ thuật Phần mềm",
    majorCode: "7480103",
    category: "Công nghệ thông tin",
    subjectGroups: ["A00", "A01", "D01"],
    benchmarkScore: 24.00,
    tuitionFee: "28.7 triệu/kỳ",
    location: "Toàn quốc",
    quota: 500,
    website: "https://fpt.edu.vn"
  },
  {
    id: 16,
    schoolCode: "FPT",
    schoolName: "Đại học FPT",
    majorName: "Thiết kế Đồ họa (Digital Art)",
    majorCode: "7210403",
    category: "Nghệ thuật - Thiết kế",
    subjectGroups: ["A00", "D01", "H00"],
    benchmarkScore: 22.50,
    tuitionFee: "28.7 triệu/kỳ",
    location: "Toàn quốc",
    quota: 200,
    website: "https://fpt.edu.vn"
  },
  {
    id: 17,
    schoolCode: "ULIS",
    schoolName: "Trường Đại học Ngoại ngữ - ĐHQGHN",
    majorName: "Ngôn ngữ Anh",
    majorCode: "7220201",
    category: "Ngôn ngữ - Xã hội",
    subjectGroups: ["D01", "D78", "D90"],
    benchmarkScore: 35.80, // thang 40
    tuitionFee: "20 - 28 triệu/năm",
    location: "Hà Nội",
    quota: 300,
    website: "https://ulis.vnu.edu.vn"
  },
  {
    id: 18,
    schoolCode: "ULIS",
    schoolName: "Trường Đại học Ngoại ngữ - ĐHQGHN",
    majorName: "Ngôn ngữ Hàn Quốc",
    majorCode: "7220210",
    category: "Ngôn ngữ - Xã hội",
    subjectGroups: ["D01", "D78", "D90"],
    benchmarkScore: 36.10, // thang 40
    tuitionFee: "20 - 28 triệu/năm",
    location: "Hà Nội",
    quota: 150,
    website: "https://ulis.vnu.edu.vn"
  }
];
