window.tailwind = window.tailwind || {};
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#acedff",
        "on-primary": "#ffffff",
        secondary: "#006c49",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        tertiary: "#005e6e",
        "primary-fixed-dim": "#b4c5ff",
        surface: "#f8f9ff",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#005236",
        background: "#f8f9ff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#00714d",
        "secondary-fixed": "#6ffbbe",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-background": "#0b1c30",
        "on-primary-fixed": "#00174b",
        "surface-tint": "#0053db",
        "inverse-on-surface": "#eaf1ff",
        "primary-container": "#2563eb",
        "on-tertiary-fixed-variant": "#004e5c",
        "primary-fixed": "#dbe1ff",
        primary: "#004ac6",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "on-tertiary-container": "#d7f6ff",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#00788c",
        "surface-dim": "#cbdbf5",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#4cd7f6",
        "secondary-container": "#6cf8bb",
        "inverse-surface": "#213145",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "on-error": "#ffffff",
        outline: "#737686",
        "on-tertiary-fixed": "#001f26",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-highest": "#d3e4fe",
        "outline-variant": "#c3c6d7",
        "inverse-primary": "#b4c5ff",
        ictu: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#0b1930",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        margin: "2rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        code: ["JetBrains Mono"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "label-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        code: ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "22px",
          { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg-mobile": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
      },
    },
  },
};
